program: experiments.py
method: grid
parameters:
  dataset:
    values:
    - 'BA_Shapes'
    - 'BA_Grid'
    - 'BA_Community'
    - 'Tree_Cycle'
    - 'Cora'
  k:
    values:
#    - 2
    - 3
#    - 5
#    - 10
  seed:
    values:
#    - 0
#    - 8
#    - 13
#    - 24
    - 42
  loss_factor:
    values:
    - 0
    - 0.2
    - 0.5
    - 1
